
server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice
  application:
    name: PRODUCT-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka